---
stages:
- build
- test
- upload
- release

render:
  stage: build
  image: golang
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - manifests
  variables:
    JSONNET_VERSION: "0.16.0"
  script:
  - go mod init dummymod
  - go get github.com/google/go-jsonnet/cmd/jsonnet@v${JSONNET_VERSION}
  - go get github.com/google/go-jsonnet/cmd/jsonnetfmt@v${JSONNET_VERSION}
  - make lint-jsonnet
  - make dashboards_out prometheus_alerts.yaml prometheus_rules.yaml

prometheus-test:
  stage: test
  image:
    name: prom/prometheus:latest
    entrypoint: [""]
  dependencies:
  - render
  needs:
  - render
  script:
  - promtool check rules manifests/prometheus_rules.yaml
  - promtool check rules manifests/prometheus_alerts.yaml
  - promtool test rules tests.yaml

upload:
  stage: upload
  image: curlimages/curl:latest
  needs:
  - render
  rules:
  - if: $CI_COMMIT_TAG  # Run this job when a tag is created manually
  script:
  - tar -czvf spinnaker-mixin.tar.gz manifests podmonitor.yaml
  - echo $CI_COMMIT_TAG
  - |
    curl \
      --header "JOB-TOKEN: $CI_JOB_TOKEN" \
      --upload-file spinnaker-mixin.tar.gz \
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/spinnaker-mixin/${CI_COMMIT_TAG}/spinnaker-mixin.tar.gz"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
  - if: $CI_COMMIT_TAG  # Run this job when a tag is created manually
  script:
  - |
    release-cli \
      create --name "Release $CI_COMMIT_TAG" \
      --tag-name $CI_COMMIT_TAG \
      --assets-link "{\"name\":\"spinnaker-mixin.tar.gz\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/spinnaker-mixin.tar.gz\"}"
